# Generated by Django 6.0.6 on 2026-06-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=100)),
                ('group_type', models.CharField(max_length=40)),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateField()),
                ('changed_by', models.CharField(max_length=40)),
                ('changed_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Moduls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateField()),
                ('changed_by', models.CharField(max_length=40)),
                ('changed_at', models.DateField()),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='guide.guide')),
            ],
        ),
    ]
