# Generated by Django 6.0.6 on 2026-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('group_type', models.CharField(max_length=40)),
                ('difficulty', models.IntegerField(null=True)),
                ('value', models.CharField(max_length=100)),
                ('ignorance', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateField()),
                ('changed_by', models.CharField(max_length=40)),
                ('changed_at', models.DateField()),
            ],
        ),
    ]
