# Generated by Django 6.0.6 on 2026-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=80)),
                ('group_type', models.CharField(max_length=40)),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateField()),
                ('changed_by', models.CharField(max_length=40)),
                ('changed_at', models.DateField()),
            ],
        ),
    ]
